import { PDFDocument, StandardFonts, rgb } from 'pdf-lib';

export type InvoicePdfInput = {
  invoiceNumber: string;
  issueDate: string;
  dueDate: string;
  currency: string;
  sellerName: string;
  buyerName: string;
  buyerEmail?: string;
  principal: number;
  interest: number;
  legalFees: number;
  totalClaim: number;
  paymentUrl?: string;
};

function money(v: number, currency: string) {
  return new Intl.NumberFormat('en-GB', { style: 'currency', currency }).format(v);
}

export async function generateProfessionalInvoicePdf(input: InvoicePdfInput): Promise<Uint8Array> {
  const pdf = await PDFDocument.create();
  const page = pdf.addPage([595.28, 841.89]); // A4
  const { width, height } = page.getSize();

  const font = await pdf.embedFont(StandardFonts.Helvetica);
  const bold = await pdf.embedFont(StandardFonts.HelveticaBold);

  let y = height - 60;

  // Header
  page.drawText('INVOICE', { x: 48, y, size: 24, font: bold, color: rgb(0.05, 0.1, 0.2) });
  y -= 26;
  page.drawText('InvoiceWarden', { x: 48, y, size: 12, font: bold, color: rgb(0.15, 0.2, 0.35) });

  // Right metadata
  page.drawText(`Invoice #: ${input.invoiceNumber}`, { x: width - 220, y: height - 60, size: 11, font });
  page.drawText(`Issue date: ${input.issueDate}`, { x: width - 220, y: height - 78, size: 11, font });
  page.drawText(`Due date: ${input.dueDate}`, { x: width - 220, y: height - 96, size: 11, font });

  // Parties
  y -= 40;
  page.drawText('Billed from', { x: 48, y, size: 10, font: bold, color: rgb(0.3, 0.35, 0.45) });
  page.drawText('Billed to', { x: 300, y, size: 10, font: bold, color: rgb(0.3, 0.35, 0.45) });

  y -= 16;
  page.drawText(input.sellerName, { x: 48, y, size: 12, font });
  page.drawText(input.buyerName, { x: 300, y, size: 12, font });
  if (input.buyerEmail) {
    y -= 14;
    page.drawText(input.buyerEmail, { x: 300, y, size: 10, font, color: rgb(0.25, 0.3, 0.4) });
  }

  // Divider
  y -= 24;
  page.drawLine({ start: { x: 48, y }, end: { x: width - 48, y }, thickness: 1, color: rgb(0.85, 0.88, 0.93) });

  // Amount breakdown table
  y -= 30;
  page.drawText('Claim breakdown', { x: 48, y, size: 12, font: bold });
  y -= 18;

  const rows: Array<[string, string]> = [
    ['Principal', money(input.principal, input.currency)],
    ['Late-payment interest', money(input.interest, input.currency)],
    ['Legal/compensation fees', money(input.legalFees, input.currency)],
    ['Total claim', money(input.totalClaim, input.currency)]
  ];

  for (const [label, value] of rows) {
    page.drawText(label, { x: 58, y, size: 11, font: label === 'Total claim' ? bold : font });
    page.drawText(value, { x: width - 190, y, size: 11, font: label === 'Total claim' ? bold : font });
    y -= 18;
  }

  y -= 14;
  page.drawText(
    'This invoice includes legally recoverable late-payment amounts under the selected jurisdiction policy.',
    { x: 48, y, size: 9, font, color: rgb(0.35, 0.4, 0.5) }
  );

  if (input.paymentUrl) {
    y -= 32;
    page.drawText('Payment link', { x: 48, y, size: 10, font: bold, color: rgb(0.3, 0.35, 0.45) });
    y -= 14;
    page.drawText(input.paymentUrl, { x: 48, y, size: 9, font, color: rgb(0.16, 0.35, 0.8) });
  }

  // Footer
  page.drawLine({ start: { x: 48, y: 70 }, end: { x: width - 48, y: 70 }, thickness: 1, color: rgb(0.9, 0.92, 0.96) });
  page.drawText('Generated by InvoiceWarden', { x: 48, y: 52, size: 9, font, color: rgb(0.45, 0.5, 0.58) });

  return pdf.save();
}
